name: Build Pipeline
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:
    name: Pytest & Flake8
    runs-on: self-hosted
    container: kalvin1234/myers-triangle
    steps:
      - name: Pull Repository
        uses: actions/checkout@v2
      - name: Install Requirements
        run: pip3 install -r requirements.txt
      - name: Pytest
        run: pytest test_foo.py test_selenium.py
      - name: Flake8
        run: flake8

